name: gcn_multi
channels:
  - pyg
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - pytorch=2.3.*
  - torchvision
  - torchaudio
  - pyg=2.6.*
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - matplotlib
  - tqdm
  - networkx
  - pyyaml
  - seaborn
  - pip
  - pip:
      - torchmetrics
      - matplotlib-inline